public with sharing class UserUtility{
	/*String UId = opp.OwnerId;
    Static String beforeRARE = "Never";
    Static String afterRARE = "Only i am an approver";//If i am an approver or delegated approver -- Only if i am an approver -- Only if i am an delegated approver
    @future(callout=true)
    public void updateUser(String UId)
    {
        User u= [Select id, Receive_Approval_Request_Emails from User where Id=:opp.OwnerId];      
        if(afterRARE){
            
			u.Receive_Approval_Request_Emails = beforeRARE;

        }else{
            u.Receive_Approval_Request_Emails = afterRARE;
        }
        update u;
    }*/
}